### DISCUSSION TITLE
Use ArtifactHub as Package Backend

### DISCUSSION THREAD

**Discussion by thschue** [glasskube/glasskube#249] [Ideas]
At the moment, Glasskube is maintaining its own information about helm charts and package versions. This information is already present in ArtifactHub (e.g. https://artifacthub.io/api/v1/packages/helm/k8sgpt/k8sgpt-operator) and I wonder if it wouldn't be easier to use information that is already there (as the package versions, location and description).

This would have the following benefits:
* Simple packages would only have to be maintained in artifacthub (the ones that can be upgraded seamlessly)
* Easy onboarding of new packages

The package specification in glasskube could look as follows:
```
[...]
artifacthub: 
  name: "cert-manager/cert-manager"
  values:
    installCRDs: "true"
```

What do you think?
