### ISSUE TITLE
Support manifests with a relative url in `package.yaml`

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#1085]
**Is your feature request related to a problem? Please describe.**
Additional manifests cannot be tested in our CI / CD pipeline and the lack of the features make private repositories harder.

**Describe the solution you'd like**
There should be an option for relative referenced manifests:

e.g.

```yaml
manifests:
  - url: ./keptn-cert.yaml
  - url: ./keptn-issuer.yaml
```

instead of

```yaml
manifests:
  - url: https://glasskube.github.io/packages/packages/keptn/v2.1.0+1/keptn-cert.yaml
  - url: https://glasskube.github.io/packages/packages/keptn/v2.1.0+1/keptn-issuer.yaml

```

**Describe alternatives you've considered**
Fixing it in our packages ci / cd pipeline.
