### ISSUE TITLE
Support Helm charts stored in container registries ( OCI images )

### ISSUE THREAD

**Issue by pmig** [glasskube/glasskube#1087]
**Is your feature request related to a problem? Please describe.**
Helm charts can also be stored in container registries. (e.g. https://github.com/glasskube/packages/pull/277 ). Glasskube doesn't support this yet.

**Describe the solution you'd like**

```yaml
helm:
  repositoryUrl: "oci://ghcr.io/spinkube/charts/spin-operator"
  chartName: "spin-operator"
  chartVersion: "0.2.0"
```

**Describe alternatives you've considered**
We can also introduce a new key e.g. `ociRepositoryUrl`.

**Additional context**
For Helm OCI we need to reference an `OCIRepository` instead of a `HelmRepository`. See: https://fluxcd.io/flux/cheatsheets/oci-artifacts/#helm-oci
