### ISSUE TITLE
Support hidden default value definitions in manifest

### ISSUE THREAD

**Issue by christophenne** [glasskube/glasskube#804]
**Is your feature request related to a problem? Please describe.**
During quickwit integration, we noticed there might be a general need for dynamic default value configurations, i.e. configurations that are dependent on the package, but the user should not be able to change them. 

For example: https://github.com/glasskube/packages/pull/139/files#diff-dfb7a579fd55c8c027910c1cd40500fad2952f96e57b58c0a634cce8d0fcc1d4R37 – here the name of the secret should include the package name, such that when multiple quickwits are installed in a namespace, each has its unique secret name. 

**Describe the solution you'd like**
There should be a new type of value configurations (name suggestions: `HIDDEN`, `STATIC`, `DEFAULT`), which are not shown on the CLI or the UI. Instead only the operator takes care of these. 

The problem described above could then be solved with the following addition to the manifest:

```
valueDefinitions:
  tlsSecretName:
    type: HIDDEN / STATIC / DEFAULT
    targets:
      - chartName: quickwit
        patch:
          op: add
          path: /ingress/tls
          valueTemplate: quickwit-tls-secret-{{ GetPackageName }}
```

where `GetPackageName` would be a newly added function that returns the package name of the evaluated package. 

**Describe alternatives you've considered**
* Provide a mechanism to template parts of the `helm.values` part of the package manifest – more likely to add confusion for package maintainers
* specifically for this case: add another `patch` to the `quickwitDomain` value – still need the `GetPackageName` function, and it would not be solved in general but only for this package.

**Additional context**
#803
