### ISSUE TITLE
Creation of `Package`/`ClusterPackage` resource should be prevented if the manifest has the wrong `scope`

### ISSUE THREAD

**Issue by kosmoz** [glasskube/glasskube#953]
**Describe the bug**
We only support the following combinations of resource type - manifest scope:
- `ClusterPackage` - `Cluster`
- `Package` - `Namespaced`

Everything else might lead to undesired behavior.

**To Reproduce**
Create a file `package.yaml` with the following contents:
```yaml
# This is WRONG! cert-manager is cluster scoped!
apiVersion: packages.glasskube.dev/v1alpha1
kind: Package
metadata:
  name: cert-manager
spec:
  packageInfo:
    name: cert-manager
    version: v1.15.1+1
```

Run `kubectl apply -f package.yaml`

**Expected behavior**
The creation should be prevented.

**Screenshots**
Creation is accepted.

**Cluster Info (please complete the following information):**
 - Type: Kubernetes
 - Version: -
 - Provider: -

**Glasskube Info (please complete the following information):**
 - Package Operator version: 0.12.1
 - CLI version:0.12.1

**Additional context**
This validation should be done by the validating admission webhook: 

https://github.com/glasskube/glasskube/blob/f9a1dfe58b3cffa2df6f2f50b4280dc29e6e8ff0/internal/webhook/package_validator.go
